### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by kitepad** [RadAd/RadNotepadMFC#1]
Download master edition. Error message as below:
1>PropertiesWnd.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\type_traits(1132,1): error C2154: '_Ty': only enumeration type is allowed as an argument to compiler intrinsic type trait '__underlying_type'
1>        with
1>        [
1>            _Ty=int
1>        ]
1>D:\RadNotepadMFC-master\src\PropertiesWnd.cpp(156): message : see reference to class template instantiation 'std::underlying_type<E>' being compiled
1>        with
1>        [
1>            E=int
1>        ]
1>D:\RadNotepadMFC-master\src\stdafx.h(69): message : see reference to function template instantiation 'std::underlying_type<_Ty>::type to_underlying(E) noexcept' being compiled
1>D:\RadNotepadMFC-master\src\PropertiesWnd.cpp(723): message : see reference to function template instantiation 'CMFCPropertyGridProperty *CreateProperty<int>(const CString &,E *,const std::initializer_list<LPCTSTR> &)' being compiled
1>        with
1>        [
1>            E=int
1>        ]
1>Done building project "RadNotepad.vcxproj" -- FAILED.

**Comment by RadAd** [comment]
Works for me but IM using 14.27.29110.
Have you tried upgrading?

**Comment by kitepad** [comment]
Solved after upgrade VS to latest build. Thanks!
Another suggestion: Provide static build with scintilla to produce single exe.

**Comment by RadAd** [comment]
Glad it's working. 
I will look into using scintilla as a static lib one day.
